# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe1dbfbc20b3bd2ae1c49a3a522dc0c707bedcc5c2c9565d39f864ff37bd33466636d375215669173e004573ea1cf5219e3a03f64799db537c98c428d15d4eb0

test:
  secret_key_base: 24f890a92baf28fcdf5919d31bfa2c540241f245b93d680b4b0776f979261c1c364e46f0ec2a60857a58e8bdc785e1e044edd5382a3d4c071d3ee0b8d46ca2c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
